# Copyright (c) 2025 ETH Zurich.
#                    All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# converts a topology generated by EvalNet into the Booksim format

def translate_topology_to_booksim(in_file, out_file, concentration):
	# read topology in the EvalNet format
	with open(in_file, "r") as file:
		next(file)
		data = file.readlines()
	# transform and write data
	node_id = 0
	with open(out_file, "w") as file:
		# transform
		for (router_id, line) in enumerate(data):	
			line_bs = "router %d" % router_id
			# add router-to-router connections
			for other_router_id in line.split(" "):
				if other_router_id != "\n":
					line_bs += " router %d" % int(other_router_id)
			# add router-to-node connections
			for i in range(concentration):
				line_bs += " node %d" % int(node_id)
				node_id += 1
			line_bs += "\n"
			# write
			file.write(line_bs)
